### ISSUE TITLE
Problem with link to file

### ISSUE THREAD

**Issue by petiard** [sumatrapdfreader/sumatrapdf#1821]
Hello!

My config:

Windows10 pro 64 bits
SumatraPDF 3.2 64 bits
MiKTeX updated

The problem:

I compile the file (in the directory D:\TeX) link_to_test.tex. That file is:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[12pt,a4paper,twoside]{article}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage[colorlinks]{hyperref}
\begin{document}
\href{test.pdf}{Link to test}
\end{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In the same directory, there is the file test.pdf.

In SumatraPDF, when I click on the link, I have the message:

« Fichier D:\TeX\file:\test.pdf#page=1 non trouvé »

and if I copy the link's address, I obtain:

file://test.pdf#page=1

With SumatraPDF 3.1.2 64 bits, there is no problem.
With Adobe Acrobat Reader DC, there is no problem. 

So, I think that's a bug...

Best regards

François Pétiard

**Comment by GitHubRulesOK** [comment]
That 3.2 bug should now be fixed about 20 days ago 
so ONLY https://www.sumatrapdfreader.org/dailybuilds.html has the fix  until next pre-release update
please try that daily version to check it resolves this issue

**Comment by GitHubRulesOK** [comment]
@kjk 
I am not convinced the latest change is working for all relative links
This may not be a typical usage but target is correctly displayed in SumatraPDF it just does not connect

[index.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5685947/index.pdf)

The relative link works  in Edge i.e. it goes up to parent folder then down into a /documents/ sub folder and there opens file Help1.pdf 

it looks like SumatraPDF pre-pends an extra / that stops the link from working, If I use copy link I see
[index.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5685947/index.pdf)

`/C:/Users/myname/Documents/help1.pdf`

**Comment by kjk** [comment]
Maybe fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/52ffe0393c104908898747c0427e75a2fb33f19e

**Comment by GitHubRulesOK** [comment]
@kjk 
That was quick but note the OP problem is that # is "tight" on .pdf ideally there should be a space

**Comment by GitHubRulesOK** [comment]
@kjk 
test files for secondary testing of hash placement
 both work in edge and should work in acrobat
 but untested so far other than they DO NOT work in 3.1.2x64
 so unclear about the OP observation that one previously worked

[Link to page2 of test.pdf in same folder with NO space before#.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5686051/Link.to.page2.of.test.pdf.in.same.folder.with.NO.space.before.pdf)
[Link to page2 of test.pdf in same folder with space before#.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5686052/Link.to.page2.of.test.pdf.in.same.folder.with.space.before.pdf)

**Comment by petiard** [comment]
> That 3.2 bug should now be fixed about 20 days ago
> so ONLY https://www.sumatrapdfreader.org/dailybuilds.html has the fix until next pre-release update
> please try that daily version to check it resolves your issue

I've tried SumatraPDF-prerel-13213-64 and the problem is still here... Same error message.

**Comment by GitHubRulesOK** [comment]
@petiard 

your case has two issues, 

1) is the extra « \file:\ » , which in **some cases** is fixed
2) you will still get _"non trouvé"_ because of **.pdf#page=1**

**Comment by GitHubRulesOK** [comment]
@kjk 
I am referencing Could not open linked pdf files #1738 here as potential duplicate
**both cases** say they worked in 3.1.2
**both cases** include a reference that attempts to open a sibling.pdf#page=1

**Comment by petiard** [comment]
> 
> 
> @petiard
> 
> your case has two issues,
> 
>     1. is the extra « \file:\ » , which in **some cases** is fixed
> 
>     2. you will still get _"non trouvé"_ because of **.pdf#page=1**
> 
> 
> there are dozens of ways TeX can be compiled to PDF so it helps if you include the PDF that works in 3.1.2

OK. Here are the two files.
Best regards.
[link_to_test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5690021/link_to_test.pdf)
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5690022/test.pdf)

**Comment by awa5114** [comment]
Has there been any progress on this issue? I'm having the same problem

**Comment by GitHubRulesOK** [comment]
@awa5114 
Which problem are you seeing without a sample I cannot tell if yours is the same as above 50% fixed and 50% not fixed.

**Comment by GitHubRulesOK** [comment]
@kjk 
Wow ! Thanks, 
I had just clicked on a link straight after auto download to 13500 expecting a fail 
and had to reload browser to see this commit as to why it was working 🙂

**Comment by GitHubRulesOK** [comment]
@awa5114 see your answer above
