### ISSUE TITLE
crashes often after last update

### ISSUE THREAD

**Issue by MarkusW71** [sumatrapdfreader/sumatrapdf#2059]
https://gist.github.com/MarkusW71/ae4fda4daea296d6a2e890a2191f29e2
Really oft, nearly 3 of 4 PDF lead to a crash
Just when opening them

**Comment by GitHubRulesOK** [comment]
there were several inter-related crash situation recently most should now be resolved
yours is running 3.4.13838 
current is 3.4.13876, seriously recommend use update

**Comment by kjk** [comment]
There are no symbols in the crash report so nothing I can do.

But like @GitHubRulesOK said, I've made lost of stability improvements in last 2 days and it's now rock solid in my stress test, so please update to latest.

If still crashes, please ensure symbols are there (with menu `Debug / Download symbols` and re-open with updated crash log
